config/routes.rb
Rails.application.routes.draw do
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  root to: "home#index"
  resources :users
  resource :session
  resources :locations
  resources :messages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :user
  belongs_to :location

  accepts_nested_attributes_for :location
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :messages
  has_many :users, through: :messages

  def self.search(search)
    where("country ILIKE ?", "%#{search}%")
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :location
  belongs_to :user
  accepts_nested_attributes_for :location
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  has_many :locations, through: :messages
  validates :username, presence: true, uniqueness: true

    # attr_accessor :password
    # # # EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i
    # validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
    # # # validates :email, :presence => true, :uniqueness => true
    # # # :format => EMAIL_REGEX
    # validates :password, :confirmation => true #password_confirmation attr
    # validates_length_of :password, :in => 6..20, :on => :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :get_current_user

 def get_current_user
   if User.exists?(session[:user_id])
     @current_user = User.find(session[:user_id])
   else
     @current_user = nil
   end
 end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if @current_user
      redirect_to locations_path
    else
      @home_page = true
    end
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.all
    if params[:search]
      @locations = Location.search(params[:search]).order("created_at DESC")
    else
      @locations = Location.all.order('created_at DESC')
    end
  end
  def show
    @location = Location.find(params[:id])
    @message = Message.new

  end


  # private
  # def location_params
  #   params.require(:location).permit(:name)
  # end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    message = Message.new(message_params)
    message.user = @current_user
    if message.save
      ActionCable.server.broadcast 'messages',
        message: message.content,
        user: message.user.first_name
      head :ok
    else
      redirect_to locations_path
    end
  end

  private

    def message_params
      params.require(:message).permit(:content, :location_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
    @user.username = cookies[:username]
  end
  def create
    input_username = params[:user][:username]
    if User.exists?(username: input_username)
      @user = User.find_by(username: input_username)
      if @user.password === params[:user][:password]
        session[:user_id] = @user.id
        cookies[:username] = {value: @user.username, expires: 1.minute.from_now}
        redirect_to user_path(@user)
      else
        flash[:alert] = "Wrong password!"
        redirect_to new_session_path
      end
    else
      flash[:alert] = "That user doesn't exist!"
      redirect_to  new_session_path
    end
  end
  def destroy
    reset_session
    flash[:notice] = "You're signed out"
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
    @location = @user.locations.build
    @location_options = Location.all.map { |l| [l.country, l.id]}
  end

  def create
    @user = User.create!(user_params)
    session[:user_id] = @user.id
    @user.locations << Location.find(params[:location_id])
    @user.save!
    redirect_to user_path(@user)
  end

  def show
    @user = User.find(params[:id])

  end

  def edit
    @user = User.find(params[:id])

    @location_options = Location.all.map { |l| [l.country, l.id]}
    redirect_to root_path unless @current_user == @user
  end

  def update
    @user = User.find(params[:id])
    @user.locations << Location.find(params[:location_id])
    redirect_to root_path unless @current_user == @user


    @user.update!(user_params)
    redirect_to user_path(@user)
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :first_name, :email, :last_name,
    :location_id,:message_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="welcome">
  <h1>Are you ready to travel?</h1>
  <button class="signIn"><%=link_to 'Join Now!', new_user_path%></button>
  <p>If you already have an account, please <%= link_to "Sign In.", new_session_path%></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Travel</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">`
  <link href="https://fonts.googleapis.com/css?family=Give+You+Glory|Port+Lligat+Slab" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="<%= @home_page ? 'homepage' : ''%>">


  <div class="<%= ! @home_page ? 'hero' : ''%>">
    <h1 class="<%= @home_page ? 'title' : '' %>"> Make Friends, Will Travel</h1>
    <h2>
      <% if @current_user %>
        <%= link_to "Hey, #{@current_user.first_name}!", user_path(@current_user) %> |
        <%= link_to "Sign Out", session_path, method: :delete %>
      <% end %>
    </h2>
  </div>

  <%= yield %>
</body>
</html>

app/views/locations/index.html.erb
<div class="locationIndex">
<h2>Where do you want to go?</h2>

<%= form_tag(locations_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Country" %>
<%= submit_tag "Search", :country => nil %>
<% end %>


 <% @locations.each do |location| %>
   <h3><%= link_to "#{location.country}", location_path(location) %></h3>
   <% end %>

</div>

app/views/locations/show.html.erb
<div class="locationShow">
<button><%= link_to "Back to Countries", locations_path %></button>
<h2>Members in <%= @location.country%>:</h2>

<ul>
  <%@location.users.distinct.each do  |user|%>
  <li>
    <%=user.first_name %>
  </li>
  <% end %>
</ul>



<div class="chat">
  <% if @location.messages.any? %>
    <div id="messages">
      <%= render partial: 'messages/message', collection: @location.messages%>
    </div>
  <%else%>
    <div class=id="messages">
    </div>
  <%end%>
</div>

  <%= render partial: 'messages/message_form', locals: {message: @message, location: @location}%>

</div>

app/views/messages/_message.html.erb
<p><strong><%=message.user.username%>:</strong> <%=message.content%></p>

app/views/messages/_message_form.html.erb
<%=form_for message, remote: true, authenticity_token: true do |f|%>
  <%= f.label :your_message%>:
  <%= f.text_area :content, class: "form-control", data: {textarea: "message"}%>

  <%= f.hidden_field :location_id, value: location.id %>
  <%= f.submit "send", class: "submitMessage", data: {send: "message"}%>
<%end%>

app/views/users/edit.html.erb
<div class="newForm">
<h2>Edit:</h2>

<%= form_for @user do |f| %>
<p>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
</p>
<p>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
</p>

<%= f.fields_for :location do |l|%>
<div class="field">
  <p>
    <%= l.label :where_do_you_currently_live? %>
    <%= select_tag(:location_id, options_for_select(@location_options))%>
  </p>
</div>
<% end %>
<p>
  <%= f.label :username %>
  <%= f.text_field :username %>
</p>
<p>
  <%= f.label :email %>
  <%= f.text_field :email %>
</p>
<p>
  <%= f.label :password %>
  <%= f.password_field :password %>
</p>
    <%= f.submit "Submit", :class => "submit" %>
  <% end %>
  </div>

app/views/users/new.html.erb
<div class="newForm">
<h2>Tell us a little about yourself:</h2>

<%= form_for @user do |f| %>
<p>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
</p>
<p>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
</p>

<%= f.fields_for :location do |l|%>
<div class="field">
  <p>
    <%= l.label :where_do_you_currently_live? %>
    <%= select_tag(:location_id, options_for_select(@location_options))%>
  </p>
</div>
<% end %>
<p>
  <%= f.label :username %>
  <%= f.text_field :username %>
</p>
<p>
  <%= f.label :email %>
  <%= f.text_field :email %>
</p>
<p>
  <%= f.label :password %>
  <%= f.password_field :password %>
</p>
<p>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <p>
    <%= f.submit "Submit", :class => "submit" %>
  <% end %>
  </div>

app/views/users/show.html.erb
<div class="userShow">
  <% if @current_user %>
    <h2>Welcome <%= @current_user.first_name %>! <span class="smaller"><%= link_to("(edit account)", edit_user_path(@current_user)) if @current_user == @user %></span></h2>
    <p>Current Location: <%=@user.locations.last.country %></p>
  <% end %>
    <p>Moved recently? Edit your account to update your location.</p>
    <button><%= link_to "Let's Get Started!", locations_path %></button>
</div>